[package]
name = "tdist"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.4.8", features = ["derive"] }
confy = "0.5.1"
crossbeam = "0.8.2"
serde = { version = "1.0.192", features = ["derive"] }
toml = "0.8.8"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
